### PR TITLE
Sentiment analysis

### PR DESCRIPTION
**Pull request by Abuton**
I built a simple streamlit app to deploy the sentiment analysis
The model i used is a logistic regression with 94% accuracy score courtesy of @Johnne32 
you can access the app online via [this link](https://share.streamlit.io/abuton/g04-brazillian-commerce/sentiment-analysis/main.py)
please review

 Thanks

### CODE REVIEW

**Comment by Abuton** [comment]
@Johnne32 i have added your model's output

**Comment by Johnne32** [comment]
> @Johnne32 i have added your model's output

Yes, I have seen it. I tested the app again with the same Portuguese words i used initially and this time, the reviews were classified correctly...yippee... I however noticed that the model is very picky because it relies very well on the training data inputs fed to it to find similar matches e.g 'defective and defect' (in Portuguese) are different for the model. If this model was trained on only English datasets, It would have been easy but the Portuguese dataset made it challenging e.g absence of the lemmatization/stemming part.

I however think that this was a very good work (Kudos to you) and could be open to more improvement if need be.  I would leave the data engineers and others to drop their reviews and we can move forward from there.

**Comment by Johnne32** [comment]
And by the way, the emojis in the web app shows in my phone but not on my system? Is it supposed to be that way?

**Comment by Abuton** [comment]
Ehm, it should be visible on all devices. If the reviews comes in I can remove it
Thank you

**Pull request merged**
