### PR TITLE
customer churn analysis

### PR DESCRIPTION
**Pull request by ugoiloh**
Hey guys,

Here's the customer churn analysis. Kindly review.

Major finding: 96% of the **Olist** customers buy only once. Hence the need for this analysis.

### CODE REVIEW

**Review by Johnne32 — APPROVED** [review]
This customer churn analysis was excellently done. The observations were clearly made and I believe this analysis clearly fit the "business perspective". Good job @ugoiloh 

One clarification though, Concerning those who got their products delivered before the deadline and gave review scores of 5 points, Are you saying that they were not necessarily satisfied and decided not to buy again even when they gave a positive review score?

**Comment by Abuton** [comment]
Nice job @ugoiloh. All the analysis are good.

I think the reduction on order volume and sales in 2018 happened because of the quantity of data we have on 2018.

**Comment by ugoiloh** [comment]
I also looked at the google reviews of customers that patronize Olist. One of their major complain is delivery time. It also takes same long time to process return and refund if the customer was not satisfied with the product or got a wrong order delivered. Those reviews can also affect the loyalty of other buyers.

**Comment by ugoiloh** [comment]
@Abuton

Yeah, you're right. Some orders has no price information on them.

**Comment by Johnne32** [comment]
> I also looked at the google reviews of customers that patronize Olist. One of their major complain is delivery time. It also takes same long time to process return and refund if the customer was not satisfied with the product or got a wrong order delivered. Those reviews can also affect the loyalty of other buyers.

I agree with you. There are some other complains like getting incomplete delivery, low quality of delivered goods and receiving defect products. These observations were covered in my analysis on the customer reviews dataset but it was not merged after our last meeting. I think I need to create another pull request as that analysis is very vital for reference purposes.

**Pull request merged**
