### PR TITLE
geo analysis

### PR DESCRIPTION
**Pull request by Oluwadurotimi10**

### CODE REVIEW

**Comment by Johnne32** [comment]
The visualizations are really interesting and nice. This was a job well done. However, I have some things to note;
a. You don't need to request review from 15 people, some of them are not even in our current group.

b. Most of the images had different colours which were a bit confusing. Is it possible to know which means which?

**Comment by BBimie** [comment]
The maps look really great @Oluwadurotimi10, good job.
I'm with @Johnne32, the maps aren't really easy to understand. A legend or an explanation of what the colours mean would definitely make it better.

**Review by Chrys97 — COMMENTED** [review]
The maps are good and I like the fact that you provided explanations of what they're about.
However, I don't know how to interpret what the colour variations mean. A legend and some explanatory notes may help.
Great job once again!

**Comment by jerry2eden** [comment]
request no longer meets projects need

**Pull request closed without merging**
