### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by waleblaq**

### CODE REVIEW

**Review by waleblaq — COMMENTED** [review]
note book on time series with price

**Review by Johnne32 — COMMENTED** [review]
This looks like some work that just contains lots of codes but no logical explanation and exact objective. Some questions:
1. Why did you combine the freight and price columns together knowing fully well that we need to predict just the price?
2.  You plotted the ACF, PACF and ARIMA plots without giving any observations or conclusions.  This is making it very difficult for proper understanding because I don't even understand the end results and what exactly was achieved!
Kindly review these. Thanks.

**Comment by waleblaq** [comment]
firstly the freight and the price makes up the total cost a customer has to pay so its the price a customer not just the order price
secondly the acf and pacf were just to get the values of p and q used in the ARIMA.
the data was splited to train prophet with about 500 samples and tested on about 100 samples with not so bad metrics
well i did not figure how to predict with the ARIMA model which i am still going to be working on and would welcome help
i would try to comment better on the code i couldnt cause i was rushing

**Comment by Johnne32** [comment]
> firstly the freight and the price makes up the total cost a customer has to pay so its the price a customer not just the order price
> secondly the acf and pacf were just to get the values of p and q used in the ARIMA.
> the data was splited to train prophet with about 500 samples and tested on about 100 samples with not so bad metrics
> well i did not figure how to predict with the ARIMA model which i am still going to be working on and would welcome help
> i would try to comment better on the code i couldnt cause i was rushing

The freight price is dependent on the distance between the seller and the customer but the order price is constant for everyone which prompted my initial question. This should also be put in consideration if we are predicting 'PRICE'

Commenting on the codes would have made it clearer. I just think this notebook should be totally reviewed and worked on for now until it becomes suitable for merging. Kudos and well done sir.

**Comment by waleblaq** [comment]
@Johnne32 check out the changes and make recommendations where necessary

**Pull request merged**
