### PR TITLE
Topic Modelling using LDA

### PR DESCRIPTION
**Pull request by Johnne32**
This notebook contains code showing how an LDA model was built to auto-generate popular topics by customers. Kindly review and let me know what you think.

### CODE REVIEW

**Comment by Abuton** [comment]
Great Job, I think the code is not complete yet like the model is not fully functional. Also I do not understand what the input will be. But this is a good idea

**Comment by Johnne32** [comment]
> Great Job, I think the code is not complete yet like the model is not fully functional. Also I do not understand what the input will be. But this is a good idea

Well, this is not a model that receives input, throw out results and gets deployed. It's one that analyses the reviews and auto-generate topics that people tend to say a lot. It's similar to analytics. Hope you get.

**Comment by Abuton** [comment]
Yes, I get now with your explanation during the meeting. Thank you

**Comment by jerry2eden** [comment]
project scope has changed

**Pull request closed without merging**
